// jhipster-mongodb/src/main/webapp/app/entities/ordered-item/ordered-item.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IOrderedItem } from 'app/shared/model/ordered-item.model';
import { Principal } from 'app/core';
import { OrderedItemService } from './ordered-item.service';

@Component({
    selector: 'jhi-ordered-item',
    templateUrl: './ordered-item.component.html'
})
export class OrderedItemComponent implements OnInit, OnDestroy {
    orderedItems: IOrderedItem[];
    currentAccount: any;
    eventSubscriber: Subscription;

    constructor(
        private orderedItemService: OrderedItemService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private principal: Principal
    ) {}

    loadAll() {
        this.orderedItemService.query().subscribe(
            (res: HttpResponse<IOrderedItem[]>) => {
                this.orderedItems = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInOrderedItems();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: IOrderedItem) {
        return item.id;
    }

    registerChangeInOrderedItems() {
        this.eventSubscriber = this.eventManager.subscribe('orderedItemListModification', response => this.loadAll());
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="jhipsterMongodbApp.orderedItem.home.title">Ordered Items</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-ordered-item" [routerLink]="['/ordered-item/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="jhipsterMongodbApp.orderedItem.home.createLabel">
            Create new Ordered Item
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="orderedItems">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="jhipsterMongodbApp.orderedItem.catalogItemId">Catalog Item Id</span></th>
            <th><span jhiTranslate="jhipsterMongodbApp.orderedItem.name">Name</span></th>
            <th><span jhiTranslate="jhipsterMongodbApp.orderedItem.price">Price</span></th>
            <th><span jhiTranslate="jhipsterMongodbApp.orderedItem.quantity">Quantity</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let orderedItem of orderedItems ;trackBy: trackId">
                <td><a [routerLink]="['/ordered-item', orderedItem.id, 'view' ]">{{orderedItem.id}}</a></td>
                <td>{{orderedItem.catalogItemId}}</td>
                <td>{{orderedItem.name}}</td>
                <td>{{orderedItem.price}}</td>
                <td>{{orderedItem.quantity}}</td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/ordered-item', orderedItem.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/ordered-item', orderedItem.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'ordered-item/'+ orderedItem.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// jhipster-mongodb-react/src/main/webapp/app/entities/ordered-item/ordered-item.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction, getSortState, IPaginationBaseState, getPaginationItemsNumber, JhiPagination } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './ordered-item.reducer';
import { IOrderedItem } from 'app/shared/model/ordered-item.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface IOrderedItemProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export type IOrderedItemState = IPaginationBaseState;

export class OrderedItem extends React.Component<IOrderedItemProps, IOrderedItemState> {
  state: IOrderedItemState = {
    ...getSortState(this.props.location, ITEMS_PER_PAGE)
  };

  componentDidMount() {
    this.getEntities();
  }

  sort = prop => () => {
    this.setState(
      {
        order: this.state.order === 'asc' ? 'desc' : 'asc',
        sort: prop
      },
      () => this.sortEntities()
    );
  };

  sortEntities() {
    this.getEntities();
    this.props.history.push(`${this.props.location.pathname}?page=${this.state.activePage}&sort=${this.state.sort},${this.state.order}`);
  }

  handlePagination = activePage => this.setState({ activePage }, () => this.sortEntities());

  getEntities = () => {
    const { activePage, itemsPerPage, sort, order } = this.state;
    this.props.getEntities(activePage - 1, itemsPerPage, `${sort},${order}`);
  };

  render() {
    const { orderedItemList, match, totalItems } = this.props;
    return (
      <div>
        <h2 id="ordered-item-heading">
          <Translate contentKey="jhipsterMongodbReactApp.orderedItem.home.title">Ordered Items</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="jhipsterMongodbReactApp.orderedItem.home.createLabel">Create new Ordered Item</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={this.sort('id')}>
                  <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('catalogItemId')}>
                  <Translate contentKey="jhipsterMongodbReactApp.orderedItem.catalogItemId">Catalog Item Id</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('name')}>
                  <Translate contentKey="jhipsterMongodbReactApp.orderedItem.name">Name</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('price')}>
                  <Translate contentKey="jhipsterMongodbReactApp.orderedItem.price">Price</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('quantity')}>
                  <Translate contentKey="jhipsterMongodbReactApp.orderedItem.quantity">Quantity</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {orderedItemList.map((orderedItem, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${orderedItem.id}`} color="link" size="sm">
                      {orderedItem.id}
                    </Button>
                  </td>
                  <td>{orderedItem.catalogItemId}</td>
                  <td>{orderedItem.name}</td>
                  <td>{orderedItem.price}</td>
                  <td>{orderedItem.quantity}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${orderedItem.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${orderedItem.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${orderedItem.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
        <Row className="justify-content-center">
          <JhiPagination
            items={getPaginationItemsNumber(totalItems, this.state.itemsPerPage)}
            activePage={this.state.activePage}
            onSelect={this.handlePagination}
            maxButtons={5}
          />
        </Row>
      </div>
    );
  }
}

const mapStateToProps = ({ orderedItem }: IRootState) => ({
  orderedItemList: orderedItem.entities,
  totalItems: orderedItem.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(OrderedItem);
