// jhipster-mongodb-react/src/main/webapp/app/entities/shipping-details/shipping-details-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './shipping-details.reducer';
import { IShippingDetails } from 'app/shared/model/shipping-details.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IShippingDetailsDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export class ShippingDetailsDetail extends React.Component<IShippingDetailsDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { shippingDetailsEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="jhipsterMongodbReactApp.shippingDetails.detail.title">ShippingDetails</Translate> [
            <b>{shippingDetailsEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="address">
                <Translate contentKey="jhipsterMongodbReactApp.shippingDetails.address">Address</Translate>
              </span>
            </dt>
            <dd>{shippingDetailsEntity.address}</dd>
          </dl>
          <Button tag={Link} to="/entity/shipping-details" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/shipping-details/${shippingDetailsEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ shippingDetails }: IRootState) => ({
  shippingDetailsEntity: shippingDetails.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ShippingDetailsDetail);

// jhipster-mongodb-with-dto/src/main/webapp/app/entities/shipping-details/shipping-details-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IShippingDetails } from 'app/shared/model/shipping-details.model';

@Component({
    selector: 'jhi-shipping-details-detail',
    templateUrl: './shipping-details-detail.component.html'
})
export class ShippingDetailsDetailComponent implements OnInit {
    shippingDetails: IShippingDetails;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ shippingDetails }) => {
            this.shippingDetails = shippingDetails;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="shippingDetails">
            <h2><span jhiTranslate="jhipsterMongodbWithDtoApp.shippingDetails.detail.title">Shipping Details</span> {{shippingDetails.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="jhipsterMongodbWithDtoApp.shippingDetails.address">Address</span></dt>
                <dd>
                    <span>{{shippingDetails.address}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/shipping-details', shippingDetails.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
