// jhipster-mongodb-with-dto-pagination/src/main/webapp/app/entities/customer-order/customer-order.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { ICustomerOrder } from 'app/shared/model/customer-order.model';
import { Principal } from 'app/core';

import { ITEMS_PER_PAGE } from 'app/shared';
import { CustomerOrderService } from './customer-order.service';

@Component({
    selector: 'jhi-customer-order',
    templateUrl: './customer-order.component.html'
})
export class CustomerOrderComponent implements OnInit, OnDestroy {
    currentAccount: any;
    customerOrders: ICustomerOrder[];
    error: any;
    success: any;
    eventSubscriber: Subscription;
    routeData: any;
    links: any;
    totalItems: any;
    queryCount: any;
    itemsPerPage: any;
    page: any;
    predicate: any;
    previousPage: any;
    reverse: any;

    constructor(
        private customerOrderService: CustomerOrderService,
        private parseLinks: JhiParseLinks,
        private jhiAlertService: JhiAlertService,
        private principal: Principal,
        private activatedRoute: ActivatedRoute,
        private router: Router,
        private eventManager: JhiEventManager
    ) {
        this.itemsPerPage = ITEMS_PER_PAGE;
        this.routeData = this.activatedRoute.data.subscribe(data => {
            this.page = data.pagingParams.page;
            this.previousPage = data.pagingParams.page;
            this.reverse = data.pagingParams.ascending;
            this.predicate = data.pagingParams.predicate;
        });
    }

    loadAll() {
        this.customerOrderService
            .query({
                page: this.page - 1,
                size: this.itemsPerPage,
                sort: this.sort()
            })
            .subscribe(
                (res: HttpResponse<ICustomerOrder[]>) => this.paginateCustomerOrders(res.body, res.headers),
                (res: HttpErrorResponse) => this.onError(res.message)
            );
    }

    loadPage(page: number) {
        if (page !== this.previousPage) {
            this.previousPage = page;
            this.transition();
        }
    }

    transition() {
        this.router.navigate(['/customer-order'], {
            queryParams: {
                page: this.page,
                size: this.itemsPerPage,
                sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
            }
        });
        this.loadAll();
    }

    clear() {
        this.page = 0;
        this.router.navigate([
            '/customer-order',
            {
                page: this.page,
                sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
            }
        ]);
        this.loadAll();
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then(account => {
            this.currentAccount = account;
        });
        this.registerChangeInCustomerOrders();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: ICustomerOrder) {
        return item.id;
    }

    registerChangeInCustomerOrders() {
        this.eventSubscriber = this.eventManager.subscribe('customerOrderListModification', response => this.loadAll());
    }

    sort() {
        const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
        if (this.predicate !== 'id') {
            result.push('id');
        }
        return result;
    }

    private paginateCustomerOrders(data: ICustomerOrder[], headers: HttpHeaders) {
        this.links = this.parseLinks.parse(headers.get('link'));
        this.totalItems = parseInt(headers.get('X-Total-Count'), 10);
        this.queryCount = this.totalItems;
        this.customerOrders = data;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="jhipsterMongodbWithDtoPaginationApp.customerOrder.home.title">Customer Orders</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-customer-order" [routerLink]="['/customer-order/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="jhipsterMongodbWithDtoPaginationApp.customerOrder.home.createLabel">
            Create new Customer Order
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="customerOrders">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="transition.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="date"><span jhiTranslate="jhipsterMongodbWithDtoPaginationApp.customerOrder.date">Date</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="status"><span jhiTranslate="jhipsterMongodbWithDtoPaginationApp.customerOrder.status">Status</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="customerId"><span jhiTranslate="jhipsterMongodbWithDtoPaginationApp.customerOrder.customer">Customer</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="paymentDetailsId"><span jhiTranslate="jhipsterMongodbWithDtoPaginationApp.customerOrder.paymentDetails">Payment Details</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="shippingDetailsId"><span jhiTranslate="jhipsterMongodbWithDtoPaginationApp.customerOrder.shippingDetails">Shipping Details</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let customerOrder of customerOrders ;trackBy: trackId">
                <td><a [routerLink]="['/customer-order', customerOrder.id, 'view' ]">{{customerOrder.id}}</a></td>
                <td>{{customerOrder.date | date:'medium'}}</td>
                <td jhiTranslate="{{'jhipsterMongodbWithDtoPaginationApp.OrderStatus.' + customerOrder.status}}">{{customerOrder.status}}</td>
                <td>
                    <div *ngIf="customerOrder.customerId">
                        <a [routerLink]="['../customer', customerOrder.customerId , 'view' ]" >{{customerOrder.customerId}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="customerOrder.paymentDetailsId">
                        <a [routerLink]="['../payment-details', customerOrder.paymentDetailsId , 'view' ]" >{{customerOrder.paymentDetailsId}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="customerOrder.shippingDetailsId">
                        <a [routerLink]="['../shipping-details', customerOrder.shippingDetailsId , 'view' ]" >{{customerOrder.shippingDetailsId}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['/customer-order', customerOrder.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/customer-order', customerOrder.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'customer-order/'+ customerOrder.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div *ngIf="customerOrders && customerOrders.length">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="queryCount" [maxSize]="5" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>
        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
    </div>
</div>

// jhipster-mongodb-react/src/main/webapp/app/entities/customer-order/customer-order.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import {
  Translate,
  ICrudGetAllAction,
  TextFormat,
  getSortState,
  IPaginationBaseState,
  getPaginationItemsNumber,
  JhiPagination
} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './customer-order.reducer';
import { ICustomerOrder } from 'app/shared/model/customer-order.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface ICustomerOrderProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export type ICustomerOrderState = IPaginationBaseState;

export class CustomerOrder extends React.Component<ICustomerOrderProps, ICustomerOrderState> {
  state: ICustomerOrderState = {
    ...getSortState(this.props.location, ITEMS_PER_PAGE)
  };

  componentDidMount() {
    this.getEntities();
  }

  sort = prop => () => {
    this.setState(
      {
        order: this.state.order === 'asc' ? 'desc' : 'asc',
        sort: prop
      },
      () => this.sortEntities()
    );
  };

  sortEntities() {
    this.getEntities();
    this.props.history.push(`${this.props.location.pathname}?page=${this.state.activePage}&sort=${this.state.sort},${this.state.order}`);
  }

  handlePagination = activePage => this.setState({ activePage }, () => this.sortEntities());

  getEntities = () => {
    const { activePage, itemsPerPage, sort, order } = this.state;
    this.props.getEntities(activePage - 1, itemsPerPage, `${sort},${order}`);
  };

  render() {
    const { customerOrderList, match, totalItems } = this.props;
    return (
      <div>
        <h2 id="customer-order-heading">
          <Translate contentKey="jhipsterMongodbReactApp.customerOrder.home.title">Customer Orders</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="jhipsterMongodbReactApp.customerOrder.home.createLabel">Create new Customer Order</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={this.sort('id')}>
                  <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('date')}>
                  <Translate contentKey="jhipsterMongodbReactApp.customerOrder.date">Date</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('status')}>
                  <Translate contentKey="jhipsterMongodbReactApp.customerOrder.status">Status</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="jhipsterMongodbReactApp.customerOrder.paymentDetails">Payment Details</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="jhipsterMongodbReactApp.customerOrder.customer">Customer</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="jhipsterMongodbReactApp.customerOrder.shippingDetails">Shipping Details</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {customerOrderList.map((customerOrder, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${customerOrder.id}`} color="link" size="sm">
                      {customerOrder.id}
                    </Button>
                  </td>
                  <td>
                    <TextFormat type="date" value={customerOrder.date} format={APP_DATE_FORMAT} />
                  </td>
                  <td>
                    <Translate contentKey={`jhipsterMongodbReactApp.OrderStatus.${customerOrder.status}`} />
                  </td>
                  <td>
                    {customerOrder.paymentDetailsCreditCardNumber ? (
                      <Link to={`payment-details/${customerOrder.paymentDetailsId}`}>{customerOrder.paymentDetailsCreditCardNumber}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {customerOrder.customerUsername ? (
                      <Link to={`customer/${customerOrder.customerId}`}>{customerOrder.customerUsername}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {customerOrder.shippingDetailsAddress ? (
                      <Link to={`shipping-details/${customerOrder.shippingDetailsId}`}>{customerOrder.shippingDetailsAddress}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${customerOrder.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${customerOrder.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${customerOrder.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
        <Row className="justify-content-center">
          <JhiPagination
            items={getPaginationItemsNumber(totalItems, this.state.itemsPerPage)}
            activePage={this.state.activePage}
            onSelect={this.handlePagination}
            maxButtons={5}
          />
        </Row>
      </div>
    );
  }
}

const mapStateToProps = ({ customerOrder }: IRootState) => ({
  customerOrderList: customerOrder.entities,
  totalItems: customerOrder.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CustomerOrder);
