// jhipster-mongodb-react/src/main/webapp/app/entities/customer-order/customer-order-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IPaymentDetails } from 'app/shared/model/payment-details.model';
import { getEntities as getPaymentDetails } from 'app/entities/payment-details/payment-details.reducer';
import { ICustomer } from 'app/shared/model/customer.model';
import { getEntities as getCustomers } from 'app/entities/customer/customer.reducer';
import { IShippingDetails } from 'app/shared/model/shipping-details.model';
import { getEntities as getShippingDetails } from 'app/entities/shipping-details/shipping-details.reducer';
import { IOrderedItem } from 'app/shared/model/ordered-item.model';
import { getEntities as getOrderedItems } from 'app/entities/ordered-item/ordered-item.reducer';
import { getEntity, updateEntity, createEntity, reset } from './customer-order.reducer';
import { ICustomerOrder } from 'app/shared/model/customer-order.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICustomerOrderUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: number }> {}

export interface ICustomerOrderUpdateState {
  isNew: boolean;
  idsorderedItems: any[];
  paymentDetailsId: number;
  customerId: number;
  shippingDetailsId: number;
}

export class CustomerOrderUpdate extends React.Component<ICustomerOrderUpdateProps, ICustomerOrderUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      idsorderedItems: [],
      paymentDetailsId: 0,
      customerId: 0,
      shippingDetailsId: 0,
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getPaymentDetails();
    this.props.getCustomers();
    this.props.getShippingDetails();
    this.props.getOrderedItems();
  }

  saveEntity = (event, errors, values) => {
    values.date = new Date(values.date);

    if (errors.length === 0) {
      const { customerOrderEntity } = this.props;
      const entity = {
        ...customerOrderEntity,
        ...values,
        orderedItems: mapIdList(values.orderedItems)
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/customer-order');
  };

  render() {
    const { customerOrderEntity, paymentDetails, customers, shippingDetails, orderedItems, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="jhipsterMongodbReactApp.customerOrder.home.createOrEditLabel">
              <Translate contentKey="jhipsterMongodbReactApp.customerOrder.home.createOrEditLabel">
                Create or edit a CustomerOrder
              </Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : customerOrderEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="customer-order-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="dateLabel" for="date">
                    <Translate contentKey="jhipsterMongodbReactApp.customerOrder.date">Date</Translate>
                  </Label>
                  <AvInput
                    id="customer-order-date"
                    type="datetime-local"
                    className="form-control"
                    name="date"
                    value={isNew ? null : convertDateTimeFromServer(this.props.customerOrderEntity.date)}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="statusLabel">
                    <Translate contentKey="jhipsterMongodbReactApp.customerOrder.status">Status</Translate>
                  </Label>
                  <AvInput
                    id="customer-order-status"
                    type="select"
                    className="form-control"
                    name="status"
                    value={(!isNew && customerOrderEntity.status) || 'CONFIRMED'}
                  >
                    <option value="CONFIRMED">
                      <Translate contentKey="jhipsterMongodbReactApp.OrderStatus.CONFIRMED" />
                    </option>
                    <option value="SHIPPED">
                      <Translate contentKey="jhipsterMongodbReactApp.OrderStatus.SHIPPED" />
                    </option>
                    <option value="DELIVERED">
                      <Translate contentKey="jhipsterMongodbReactApp.OrderStatus.DELIVERED" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="paymentDetails.creditCardNumber">
                    <Translate contentKey="jhipsterMongodbReactApp.customerOrder.paymentDetails">Payment Details</Translate>
                  </Label>
                  <AvInput id="customer-order-paymentDetails" type="select" className="form-control" name="paymentDetailsId">
                    <option value="" key="0" />
                    {paymentDetails
                      ? paymentDetails.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.creditCardNumber}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="customer.username">
                    <Translate contentKey="jhipsterMongodbReactApp.customerOrder.customer">Customer</Translate>
                  </Label>
                  <AvInput id="customer-order-customer" type="select" className="form-control" name="customerId">
                    <option value="" key="0" />
                    {customers
                      ? customers.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.username}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="shippingDetails.address">
                    <Translate contentKey="jhipsterMongodbReactApp.customerOrder.shippingDetails">Shipping Details</Translate>
                  </Label>
                  <AvInput id="customer-order-shippingDetails" type="select" className="form-control" name="shippingDetailsId">
                    <option value="" key="0" />
                    {shippingDetails
                      ? shippingDetails.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.address}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="orderedItems">
                    <Translate contentKey="jhipsterMongodbReactApp.customerOrder.orderedItems">Ordered Items</Translate>
                  </Label>
                  <AvInput
                    id="customer-order-orderedItems"
                    type="select"
                    multiple
                    className="form-control"
                    name="orderedItems"
                    value={customerOrderEntity.orderedItems && customerOrderEntity.orderedItems.map(e => e.id)}
                  >
                    <option value="" key="0" />
                    {orderedItems
                      ? orderedItems.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.name}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/customer-order" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  paymentDetails: storeState.paymentDetails.entities,
  customers: storeState.customer.entities,
  shippingDetails: storeState.shippingDetails.entities,
  orderedItems: storeState.orderedItem.entities,
  customerOrderEntity: storeState.customerOrder.entity,
  loading: storeState.customerOrder.loading,
  updating: storeState.customerOrder.updating
});

const mapDispatchToProps = {
  getPaymentDetails,
  getCustomers,
  getShippingDetails,
  getOrderedItems,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CustomerOrderUpdate);

// jhipster-mongodb/src/main/webapp/app/entities/customer-order/customer-order-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';
import { JhiAlertService } from 'ng-jhipster';

import { ICustomerOrder } from 'app/shared/model/customer-order.model';
import { CustomerOrderService } from './customer-order.service';
import { ICustomer } from 'app/shared/model/customer.model';
import { CustomerService } from 'app/entities/customer';
import { IPaymentDetails } from 'app/shared/model/payment-details.model';
import { PaymentDetailsService } from 'app/entities/payment-details';
import { IShippingDetails } from 'app/shared/model/shipping-details.model';
import { ShippingDetailsService } from 'app/entities/shipping-details';
import { IOrderedItem } from 'app/shared/model/ordered-item.model';
import { OrderedItemService } from 'app/entities/ordered-item';

@Component({
    selector: 'jhi-customer-order-update',
    templateUrl: './customer-order-update.component.html'
})
export class CustomerOrderUpdateComponent implements OnInit {
    private _customerOrder: ICustomerOrder;
    isSaving: boolean;

    customers: ICustomer[];

    paymentdetails: IPaymentDetails[];

    shippingdetails: IShippingDetails[];

    ordereditems: IOrderedItem[];
    date: string;

    constructor(
        private jhiAlertService: JhiAlertService,
        private customerOrderService: CustomerOrderService,
        private customerService: CustomerService,
        private paymentDetailsService: PaymentDetailsService,
        private shippingDetailsService: ShippingDetailsService,
        private orderedItemService: OrderedItemService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ customerOrder }) => {
            this.customerOrder = customerOrder;
        });
        this.customerService.query().subscribe(
            (res: HttpResponse<ICustomer[]>) => {
                this.customers = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.paymentDetailsService.query().subscribe(
            (res: HttpResponse<IPaymentDetails[]>) => {
                this.paymentdetails = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.shippingDetailsService.query().subscribe(
            (res: HttpResponse<IShippingDetails[]>) => {
                this.shippingdetails = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.orderedItemService.query().subscribe(
            (res: HttpResponse<IOrderedItem[]>) => {
                this.ordereditems = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.customerOrder.date = moment(this.date, DATE_TIME_FORMAT);
        if (this.customerOrder.id !== undefined) {
            this.subscribeToSaveResponse(this.customerOrderService.update(this.customerOrder));
        } else {
            this.subscribeToSaveResponse(this.customerOrderService.create(this.customerOrder));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<ICustomerOrder>>) {
        result.subscribe((res: HttpResponse<ICustomerOrder>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackCustomerById(index: number, item: ICustomer) {
        return item.id;
    }

    trackPaymentDetailsById(index: number, item: IPaymentDetails) {
        return item.id;
    }

    trackShippingDetailsById(index: number, item: IShippingDetails) {
        return item.id;
    }

    trackOrderedItemById(index: number, item: IOrderedItem) {
        return item.id;
    }

    getSelected(selectedVals: Array<any>, option: any) {
        if (selectedVals) {
            for (let i = 0; i < selectedVals.length; i++) {
                if (option.id === selectedVals[i].id) {
                    return selectedVals[i];
                }
            }
        }
        return option;
    }
    get customerOrder() {
        return this._customerOrder;
    }

    set customerOrder(customerOrder: ICustomerOrder) {
        this._customerOrder = customerOrder;
        this.date = moment(customerOrder.date).format(DATE_TIME_FORMAT);
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-customer-order-heading" jhiTranslate="jhipsterMongodbApp.customerOrder.home.createOrEditLabel">Create or edit a Customer Order</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!customerOrder.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="customerOrder.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="jhipsterMongodbApp.customerOrder.date" for="field_date">Date</label>
                    <div class="d-flex">
                        <input id="field_date" type="datetime-local" class="form-control" name="date" [(ngModel)]="date"
                        />
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="jhipsterMongodbApp.customerOrder.status" for="field_status">Status</label>
                    <select class="form-control" name="status" [(ngModel)]="customerOrder.status" id="field_status" >
                        <option value="CONFIRMED">{{'jhipsterMongodbApp.OrderStatus.CONFIRMED' | translate}}</option>
                        <option value="SHIPPED">{{'jhipsterMongodbApp.OrderStatus.SHIPPED' | translate}}</option>
                        <option value="DELIVERED">{{'jhipsterMongodbApp.OrderStatus.DELIVERED' | translate}}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="jhipsterMongodbApp.customerOrder.customer" for="field_customer">Customer</label>
                    <select class="form-control" id="field_customer" name="customer" [(ngModel)]="customerOrder.customer" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="customerOption.id === customerOrder.customer?.id ? customerOrder.customer : customerOption" *ngFor="let customerOption of customers; trackBy: trackCustomerById">{{customerOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="jhipsterMongodbApp.customerOrder.paymentDetails" for="field_paymentDetails">Payment Details</label>
                    <select class="form-control" id="field_paymentDetails" name="paymentDetails" [(ngModel)]="customerOrder.paymentDetails" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="paymentDetailsOption.id === customerOrder.paymentDetails?.id ? customerOrder.paymentDetails : paymentDetailsOption" *ngFor="let paymentDetailsOption of paymentdetails; trackBy: trackPaymentDetailsById">{{paymentDetailsOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="jhipsterMongodbApp.customerOrder.shippingDetails" for="field_shippingDetails">Shipping Details</label>
                    <select class="form-control" id="field_shippingDetails" name="shippingDetails" [(ngModel)]="customerOrder.shippingDetails" >
                        <option [ngValue]="null"></option>
                        <option [ngValue]="shippingDetailsOption.id === customerOrder.shippingDetails?.id ? customerOrder.shippingDetails : shippingDetailsOption" *ngFor="let shippingDetailsOption of shippingdetails; trackBy: trackShippingDetailsById">{{shippingDetailsOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label jhiTranslate="jhipsterMongodbApp.customerOrder.orderedItems" for="field_orderedItems">Ordered Items</label>
                    <select class="form-control" id="field_orderedItems" multiple name="orderedItems" [(ngModel)]="customerOrder.orderedItems">
                        <option [ngValue]="getSelected(customerOrder.orderedItems, orderedItemOption)" *ngFor="let orderedItemOption of ordereditems; trackBy: trackOrderedItemById">{{orderedItemOption.name}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
